import random

customer_list = (
    'Đặng Tuấn Anh',
    'Hoàng Đức Anh',
    'Lưu Trang Anh',
    'Phạm Hoàng Anh',
    'Phạm Thị Hiền Anh',
    'Phạm Khắc Việt Anh',
    'Đỗ Hoàng Gia Bảo',
    'Trần Thị Minh Châu',
    'Tăng Phương Chi',
    'Gan Feng Du',
    'Phạm Tiến Dũng',
    'Nguyễn Thái Dương',
    'Trần An Dương',
    'Mạc Trung Đức',
    'Vũ Hương Giang',
    'Nguyễn Thị Ngân Hà',
    'Nguyễn Lê Hiếu',
    'Phạm Xuân Hòa',
    'Khoa Minh Hoàng',
    'Nguyễn Hữu Hiệp Hoàng',
    'Nguyễn Mạnh Hùng',
    'Nguyễn Vũ Gia Hưng',
    'Trần Tuấn Hưng',
    'Phạm Gia Minh',
    'Đỗ Hoàng Mỹ',
    'Đỗ Quang Ngọc',
    'Đàm Yến Nhi',
    'Đoàn Hoàng Sơn',
    'Nguyễn Công Thành',
    'Bùi Phương Thảo',
    'Nguyễn Hương Thảo',
    'Tô Diệu Thảo',
    'Vũ Phương Thảo',
    'Đặng Huyền Thi',
    'Đặng Thành Trung',
    'Trịnh Thiên Trường',
    'Lê Khánh Vy',
    'Phạm Bảo Liên',
    'Đinh Thùy Linh',
    'Nguyễn Thùy Linh',
    'Đỗ Hà Linh',
    'Vũ Thùy Linh',
    'Đỗ Thùy Linh',
    'Hoàng Nhật Mai',
    'Nguyễn Trọng Minh',
    'Ngô Gia Minh',
    'Mai Hoàng Minh',
    'Đỗ Hải Nam',
    'Trần Bảo Ngân',
    'Trần Kim Ngân',
    'Đỗ Minh Ngọc',
    'Bùi Khánh Ngọc',
    'Trần Uyên Nhi',
    'Phạm Đặng Gia Như',
    'Lê Tất Hoàng Phát',
    'Đào Tuấn Phong',
    'Nguyễn Phú Hải Phong',
    'Trần Trung Phong',
    'Bùi Thành Tài',
    'Đặng Thanh Thảo',
    'Nguyễn Trường Thịnh',
    'Dương Phúc Thịnh',
    'Nguyễn Minh Thư',
    'Bùi Trung Minh Trí',
    'Hoàng Quốc Trung',
    'Vũ Hữu Minh Tường',
    'Lê Thị Phương Vy',
    'Nguyễn Hùng Anh',
    'Nguyễn Ngọc Anh',
    'Mai Tùng Bách',
    'Nguyễn Trần Bình',
    'Vũ Điệp Chi',
    'Phạm Văn Đạt',
    'Hoàng An Đông',
    'Vũ Trung Đức',
    'Phí Vũ Trí Đức',
    'Đặng Gia Hân',
    'Lưu Ngọc Hiền',
    'Phạm Ngọc Hiếu',
    'Phạm Sỹ Hiếu',
    'Phạm Phương Hoa',
    'Vũ Đức Huy',
    'Vũ Thanh Huyền',
    'Phạm Thu Huyền',
    'Nguyễn Tuấn Hưng',
    'Trần Đức Hưng',
    'Nguyễn Tiến Hưng',
    'Lê Nguyễn Diệu Hương',
    'Nguyễn Hữu Ngọc Khánh',
    'Bùi Nam Khánh',
    'Đinh Ngọc Khánh',
    'Hồ Nguyễn Minh Khuê',
    'Phạm Vũ Diệp Lam',
    'Đinh Hoàng Tùng Lâm',
    'Lê Quang Long',
    'Phạm Thị Phương Mai',
    'Lê Trần Tuấn Minh',
    'Nguyễn Thị Bích Ngọc',
    'Lê Trung Nguyên',
    'Lê Quỳnh Nhi',
    'Nguyễn Tuyết Anh Nhi',
    'Đinh Phú Sang',
    'Đào Duy Thái',
    'Vũ Minh Thư',
    'Vũ Thế Hưng',
    'Hà Duy Anh ',
    'Đồng Đức Anh ',
    'Vũ Ngân Anh ',
    'Trần Mai Quỳnh Anh',
    'Nguyễn Thị Tùng Chi',
    'Phạm Quang Dũng',
    'Nguyễn Tùng Dương',
    'Phạm Đức Đạt ',
    'Nguyễn Hải Đông ',
    'Nguyễn Duy Đức',
    'Nguyễn Vũ Minh Đức',
    'Trịnh Việt Đức',
    'Lưu Hương Giang',
    'Quản Gia Hân ',
    'Nguyễn Trọng Hiếu ',
    'Nguyễn Quang Hùng',
    'Trần Gia Huy',
    'Đặng Vũ Huy',
    'Phạm Ngọc Huyền',
    'Trần Ngọc Khánh',
    'Bùi Đức Kiên ',
    'Bùi Hải Lâm ',
    'Dương Khánh Linh',
    'Trần Huy Hoàng Linh',
    'Trần Nhật Long',
    'Trần Đức Lương',
    'Nguyễn Đức Minh',
    'Đoàn Hải Minh',
    'Mai Xuân Minh ',
    'Bùi Xuân Nam ',
    'Bùi Khánh Ngọc ',
    'Mai Phương Ngọc ',
    'Nguyễn Yến Nhi ',
    'Đinh Ngọc Quỳnh Như',
    'Nguyễn Minh Phương',
    'Nguyễn Minh Quân ',
    'Nguyễn Thúy Quỳnh ',
    'Lê Thị Minh Tâm ',
    'Hoàng Đức Thành',
    'Nguyễn Đức Thiện',
    'Phạm Thị Thu Trang',
    'Hoàng Quang Hưng',
    'Đỗ Quốc Thắng',
    'Phạm Mạnh Hùng',
    'Lương Thị Thúy An',
    'Bùi Quỳnh Anh',
    'Phạm Phương Anh',
    'Phạm Hoàng Bách',
    'Đoàn Việt Bách',
    'Trần Lê Gia Bảo',
    'Bùi Ngọc Chi',
    'Ng Hoàng Kim Cương',
    'Hoàng Trung Dũng',
    'Phạm Anh Duy',
    'Bùi Công Duy',
    'Bùi Nhật Dương',
    'Đỗ Duy Đoàn',
    'Đỗ Duy Hải',
    'Lương Bảo Hân',
    'Đỗ Gia Hân',
    'Nguyễn Đức Hiếu',
    'Phạm Gia Huy',
    'Nguyễn Minh Huyền',
    'Bùi Công Khanh',
    'Nguyễn Hoàng Lâm',
    'Văn Tiến Long',
    'Hoàng Hải Minh',
    'Nguyễn Tuấn Minh',
    'Đỗ Trần Nam',
    'Trần Đức Nam',
    'Nguyễn Bảo Nam',
    'Trần Vũ Hà Ngân',
    'Phạm Trần Lan Nhi',
    'Nguyễn Đăng Phong',
    'Bùi An Phú',
    'Đỗ Đức Phúc',
    'Nguyễn Hồng Phúc',
    'Bùi Đàm Mai Phương',
    'Phạm Minh Phương',
    'Nguyễn Hữu Thành',
    'Lại Hương Thảo',
    'Nguyễn Quang Thiện',
    'Bùi Quang Tín',
    'Lê Vi Phương Trinh',
    'Vũ Hiểu Trung',
    'Nguyễn Hoàng Vy',
    'Vũ Hải Hà An',
    'Phạm Thế An',
    'Nguyễn Tô Lân Anh',
    'Trần Hoàng Anh',
    'Phạm Trúc Anh',
    'Nguyễn Thùy Anh',
    'Nguyễn Thảo Anh',
    'Đoàn Duy Bảo',
    'Lê Thùy Chi',
    'Trần Việt Cường',
    'Dương Minh Dũng',
    'Lê Sỹ Dũng',
    'Nguyễn Thế Duy',
    'Nguyễn Ngọc Hà',
    'Nguyễn Đức Gia Hòa',
    'Đào Thanh Huy',
    'Đào Nguyên Gia Huy',
    'Ng Hữu Bình Hưng',
    'Lê Hoàng Hưng',
    'Đoàn Vĩnh Hưng',
    'Đặng Hữu Khánh',
    'Bùi Nam Khánh',
    'Vũ Thiện Khiêm',
    'Đoàn Bá Khuyến',
    'Trần Phương Linh',
    'Vũ Tú Linh',
    'Đỗ Vũ Ngọc Linh',
    'Hoàng Phương Linh',
    'Hoàng Lê Minh Long',
    'Ng Thị Ngọc Lương',
    'Nguyễn Như Mai',
    'Hoàng Duy Minh',
    'Vũ Đặng Khánh My',
    'Vũ Ngọc Hiếu Ngân',
    'Hà Huy Tùng Nguyên',
    'Phạm Bá Phú',
    'Hoàng Thế Quang',
    'Trần Bảo Thy',
    'Quản Hữu Toàn',
    'Nguyễn Việt Trinh',
    'Đỗ Phúc Hiếu Tuệ',
    'Phạm Duy Tùng',
    'Vũ Đặng Hoàng Vũ',
    'Đào Thảo',
    'Đỗ Đức ',
    'Nguyễn Minh',
    'Nguyễn P Phương',
    'Phạm Nhật',
    'Phạm Tuệ',
    'Vũ Minh ',
    'Vũ Minh ',
    'Nguyễn Thanh',
    'Đặng Nhật Minh',
    'Nguyễn Anh',
    'Nguyễn Ngân',
    'Nguyễn Phạm Hải',
    'Vũ Trọng ',
    'Nguyễn Tiến ',
    'Ngô Kim',
    'Bùi Lam',
    'An Gia ',
    'Đoàn Phạm Ngọc',
    'Nguyễn Hoàng',
    'Trương Hồng ',
    'Phạm Xuân',
    'Vũ Hoàng',
    'Dương Gia ',
    'Hà Trần Thảo',
    'Nguyễn Quỳnh',
    'Bùi Thảo',
    'Phạm Hải Đức ',
    'Nguyễn Việt ',
    'Đỗ Phạm Hoàng ',
    'Nguyễn Hào',
    'Nguyễn Thế',
    'Vũ Anh',
    'Phùng Phương',
    'Đoàn Thu',
    'Lê Khánh Hà',
    'Dương Khoa ',
    'Lương Ngọc Anh',
    'Nguyễn Ngọc Diệp Anh',
    'Bùi Ngọc Phương Anh',
    'Đồng Mai Phương Anh',
    'Nguyễn Dương Quang Anh',
    'Phạm Đức Anh',
    'Nguyễn Hoàng Duy',
    'Trần Hồng Dương',
    'Nguyễn Hoàng Gia',
    'Phạm Vân Hà',
    'Lưu Hoàng Hải',
    'Phạm Dương Hằng',
    'Vũ Quốc Huy',
    'Nguyễn Duy Hưng',
    'Trần Duy Hưng',
    'Trần Khánh Linh',
    'Phạm Quang Minh',
    'Phạm Hà My',
    'Lê My',
    'Trần Tiến Nam',
    'Nguyễn Song Thành Nam',
    'Nguyễn Hà Ngân',
    'Vũ Minh Ngọc',
    'Nguyễn Vũ Bảo Ngọc',
    'Nguyễn Thiên Ngọc',
    'Nguyễn Yến Nhi',
    'Nguyễn Minh Phượng',
    'Nguyễn Hải Sơn',
    'Nguyễn Đoàn Đức Thành',
    'Nguyễn Dương Thành',
    'Đào Hồng Thiện',
    'Nguyễn Ngọc Hà Trang',
    'Phạm Nguyễn Minh Trí',
    'Phạm Hoàng Việt',
    'Mạc Nguyễn Hà Vy',
    'Lê Minh Châu',
    'Ng. Hoàng Tiến  Dũng',
    'Đỗ Thùy Dương',
    'Vũ Bá Đại',
    'Trần Tuấn Đạt',
    'Vũ Nhân Đức',
    'Trần Minh Đức',
    'Nguyễn Đình Đức',
    'Lương Trần Bảo Hà',
    'Phạm Nguyễn Bảo Hân',
    'Vũ Minh Hoàng',
    'Trần Quốc Khánh',
    'Lê Nguyễn Hà Linh',
    'Nguyễn Thị Phương Linh',
    'Lê Minh Long',
    'Lã Hiền Minh',
    'Phạm Trần Hoàng Minh',
    'Nguyễn Trung Nghĩa',
    'Nguyễn Thị Minh Ngọc',
    'Phạm Minh Nhật',
    'Phạm Nhiên Khánh Nhi',
    'Nguyễn Hoàng Bảo Nhi',
    'Cao Nguyễn Bảo Phúc',
    'Hoàng Gia Trọng Phúc',
    'Nguyễn Đăng Quang',
    'Đào Thiện Anh Quân',
    'Nguyễn Đức Toàn',
    'Tô Ngọc Trang',
    'Lương Lê Ngọc BảoTrân',
    'Nguyễn Minh Triết',
    'Nguyễn Trung Trực',
    'Đỗ Minh Tuấn',
    'Nguyễn Hoàng Tùng',
    'Phạm Bích Ngọc',
    'LươngNgọc Thắng',
    'Ng.Hồng Quang',
    'Ng.Trung Thành',
    'Đỗ Văn Hiền',
    'Ng.Hoàng Chiến',
    'Đặng Quốc Việt',
    'Hoàng Văn Bảo',
    'Lưu Thanh Tuấn',
    'Hoàng Thị Thanh Mai',
    'Nguyễn Quỳnh Hoa',
    'Cao Thị Xuân Dung',
    'Đỗ Hồng Việt',
    'Phạm Thị Thu Hương',
    'Bùi Thị Vân Thiện',
    'Nguyễn Thị Thu Hiền',
    'Nguyễn Thị Trà My',
    'Trần Thị Thúy',
    'Trần Trọng Dũng',
    'Mạc Văn Việt',
    'Bùi Thị Thu Hương',
    'Nguyễn Văn Đạm',
    'Lê Thị Hợi',
    'Phạm Văn Cường',
    'Khoa Năng Tùng',
    'Nguyễn Hữu Hòa',
    'Nguyễn Vân Long',
    'Nguyễn Thị Dương',
    'Tô Thị Mai',
    'Phạm Duy',
    'Bùi Phạm Vân Anh',
    'Đỗ Quang Minh',
    'Nguyễn Thị Thu Hằng',
    'Cao Thị Phương Thảo',
    'Nguyễn Thị Việt Yên',
    'Bùi Văn Quân',
    'Nguyễn Thị Hương',
    'Tô Sỹ Ngọc',
    'Vũ Duy Phương',
    'Phạm Thị Thanh Thùy',
    'Nguyễn Thị Mai',
    'Trịnh Đình Minh',
    'Nguyễn Thế Tài',
    'Phạm văn Nam',
    'Đinh Trọng Hiệp',
    'Nguyễn Mạnh Hùng',
    'Đỗ Văn Tấn',
    'Vũ Văn Thắng',
    'Đỗ Trọng Đức',
    'Hoàng Đại Thắng',
    'Nguyễn Văn Chung',
    'Ngô Văn Hiệp',
    'Mai Văn Bình',
    'Đỗ Mạnh Huy',
    'Trần Đức Trung',
    'Trần Hoài Phương',
    'Đỗ Văn Phương',
    'Bùi Mạnh Hùng',
    'Trần Anh Thi',
    'Phạm  Gia Mạnh',
    'Lê Tất Thế',
    'Đào Hồng Cẩm',
    'Nguyễn Văn Phúc',
    'Trần Trung Dũng',
    'Bùi Đình Hùng',
    'Đặng Văn Toán',
    'Nguyễn Văn Trường ',
    'Dương Văn Hà',
    'Nguyễn Quốc Tú',
    'Bùi Trung Huấn',
    'Hoàng Tiến Dũng',
    'Vũ Hữu Thiện',
    'Nguyễn Mạnh Hùng',
    'Phạm Thị Bích Ngọc',
    'Nguyễn Thúy Hảo',
    'Trần Thị Hường',
    'Phạm Thị Phượng',
    'Nguyễn Thị Bích Thúy',
    'Vũ Thị Văn Thường',
    'Đoàn Thị Thu Huyền',
    'Vũ Thị Kim Chung',
    'Nguyễn Thu Hương',
    'Nguyễn Thị Hương',
    'Vũ Thị Hưng',
    'Nguyễn Thị Hường',
    'Vũ Thị Phương Mai',
    'Nguyễn Thị Thắm',
    'Đoàn Thị Hương',
    'Phạm Thu Hương',
    'Ngô Thị Minh Phương',
    'Nguyễn Thị Hằng Nga',
    'Nguyễn Diệu Hương',
    'Nguyễn Thu Hoài',
    'Nguyễn Thị Lý',
    'Hoàng Thị Hương',
    'Trần Thanh Diệp',
    'Nguyễn Quỳnh Giang',
    'Vũ Thị Thu Hương',
    'Hoàng Thị Bích Ngọc',
    'Trần Thị Thanh Tâm',
    'Nguyễn Thị Phương',
    'Trần Diễm Thùy Dương',
    'Phạm Thị Kim Phúc',
    'Trần Thị Hảo',
    'Bùi Thị Kim Oanh',
    'Phạm Ánh Tuyết',
    'Đặng Thùy Vân',
    'Nguyễn Bích Thủy',
    'Hà Quang Phong',
    'Đồng Thanh Phương',
    'Vũ Đức Nghĩa',
    'Trần Đức Hoàn',
    'Nguyễn Thanh Tùng',
    'Phạm Hồng Sơn',
    'Nguyễn Mạnh Dũng',
    'Phạm Văn Công',
    'Nguyễn Hồng Nam ',
    'Nguyễn Duy Hùng',
    'Nguyễn Bình Minh',
    'Trịnh Xuân Cường',
    'Lưu Văn Tuấn',
    'Quản Văn Tạo ',
    'Nguyễn Thị Linh',
    'Nguyễn Quang Thắng',
    'Trần Thanh Tùng',
    'Đặng Hưng Thịnh ',
    'Phạm Đức Thắng',
    'Trân Thành',
    'Bùi Thanh Tùng',
    'Bùi Trường Sơn',
    'Dương Thế Tùng',
    'Trân Tăng Xuân',
    'Đào Xuân Mạnh',
    'Trần  Hoàn',
    'Nguyễn Đức Thuân',
    'Đoàn Thế Hưng',
    'Mai Xuân Khải',
    'Bùi Bình Minh',
    'Bùi Văn Đạt',
    'Mai Ngọc Tấn',
    'Nguyễn Khanh Hoài',
    'Đinh Văn Điễn',
    'Nguyễn Đức Tiến',
    'Nguyễn Văn Hùng',
    'Nguyễn Anh Tuấn',
    'Lê Bình Nguyên',
    'Vũ hải Thanh',
    'Phạm Thế Anh',
    'Ng. Thị Mai Hương',
    'Trần Đoàn Viện ',
    'Phạm Hữu Nguyên',
    'Ng Bảo Long',
    'Ng Thiết Dân',
    'Đoàn bảo Thanh',
    'Lê Văn Thông',
    'Trần Ngoc Vinh',
    'Dương Việt Cường',
    'Lê Sỹ Trị',
    'Nguyễn Thế Đức',
    'Ng Kim Hoằng',
    'Nguyễn Thế Huy',
    'Đào Thanh Tuấn',
    'Đào Ng Gia Huy',
    'Ng Hữu Trọng',
    'Đoàn Hữu Phong',
    'Đặng Hữu Trung',
    'Bùi Trọng Nghĩa',
    'Vũ Quang Hợp',
    'Đoàn Văn Trung',
    'Trần Trọng Tâm',
    'Vũ Văn Thắng',
    'Đỗ Hoài Sơn',
    'Hoàng Trung Quân',
    'Hoàng  Lê Hưng',
    'Nguyễn Thế Kiên',
    'Nguyễn  Khắc Hải',
    'Hoàng Duy Thành ',
    'Đặng T Vân  Anh',
    'Vũ văn Trọng',
    'Hà Huy Tùng',
    'Phạm Duy Quảng',
    'Hoàng Văn Tình',
    'Đỗ Hoài Sơn',
    'Phạm Ngọc Long',
    'Vũ Hồng Thắng',
    'Đào Văn Thuyết',
    'Đỗ Mạnh Đức',
    'Nguyễn Trung Nghĩa',
    'Nguyễn Xuân Thứ',
    'Phạm Quang Huy',
    'Phạm Trung Thái',
    'Vũ Mạnh Toàn',
    'Vũ Việt Thắng ',
    'Nguyễn Văn Thắng',
    'Đặng Hồng Sơn',
    'Nguyễn Văn Kỳ',
    'Nguyễn Hoàng Chương',
    'Nguyễn Xuân Trí',
    'Vũ Đức Thiện',
    'Nguyễn Tiến Dũng',
    'Ngô Minh Tuân',
    'Bùi Xuân Trường',
    'An Sơn Hà',
    'Đoàn Ngọc Lâm',
    'Nguyễn Văn Tá',
    'Trương  Tuấn Lợi',
    'Phạm Quang Huy',
    'Vũ Việt Hà',
    'Dương Anh Sơn',
    'Hà Văn Thắng',
    'Nguyễn Bá Sơn',
    'Bùi Đức Thìn',
    'Phạm Hải Nam',
    'Nguyễn Việt Phương',
    'Đỗ Văn Tú',
    'Nguyễn Ngọc Hà',
    'Lê Mạnh Hùng',
    'Dương Anh Tuấn',
    'NGUYỄN PHƯƠNG AN',
    'ĐINH THỊ CHUYÊN',
    'GIÀNG THỊ ĐIỆP',
    'LÊ THỊ THU ĐÔNG',
    'NGUYỄN THỊ DUYÊN',
    'NGUYỄN THỊ THU HÀ',
    'NGUYỄN THỊ THU HÀ',
    'NGUYỄN THỊ HẰNG',
    'PHẠM THỊ HẠNH',
    'NGUYỄN ANH HÀO',
    'LƯU THỊ THANH HUYỀN',
    'NGUYỄN VĂN LONG',
    'NGUYỄN HOÀI NAM',
    'NGÔ MINH NHÂN',
    'LÊ THỊ PHÚC',
    'BÙI THỊ PHƯƠNG',
    'PHẠM THỊ MAI QUYÊN',
    'PHẠM HƯƠNG QUỲNH',
    'NGUYỄN VĂN THĂNG',
    'NGUYỄN THỊ THẮNG',
    'VŨ THỊ PHƯƠNG THẢO',
    'NGUYỄN THỊ THUẬN',
    'NGUYỄN THỊ THUẬN',
    'LÊ THỊ THÚY',
    'PHẠM THỊ HỒNG THỦY',
    'NGUYỄN VĂN TÍN',
    'LÊ QUANG TRƯỜNG',
    'VŨ THỊ THANH TUYỀN',
    'NGUYỄN THỊ VÂN',
    'Huỳnh Thị Kim Anh',
    'Phan Hải Ánh',
    'Nguyễn Thái Bình',
    'Lê Viết Cảnh',
    'Võ Nguyễn Quỳnh Châu',
    'Châu Khắc Nhật Cường',
    'Lê Viết Cường',
    'Nguyễn Thanh Diễm',
    'Huỳnh Anh Duy',
    'Lê Phước Đạt',
    'Bùi Cao Hoàng Đăng',
    'Lưu Đinh Đại Đức',
    'Phạm Thị Trà Giang',
    'Nguyễn Hoàng Phương Hân',
    'Lê Thị Thu Hiền',
    'Võ Xuân Hiếu',
    'Nguyễn Hồng Hiệp',
    'Lâm Duy Hoàng',
    'Trần Thị Thanh Hòa',
    'Nguyễn Hữu Hoàng Hưng',
    'Nguyễn Văn Nhật Huy',
    'Nguyễn Văn Nhật Huy',
    'Phạm Quang Huy',
    'Tôn Thất Nhật Huy',
    'Đinh Thị Thanh Huyền',
    'Phan Văn Bảo Khang',
    'Nguyễn Đình Minh Khôi',
    'Nguyễn Khoa Lân',
    'Phạm Khắc Long',
    'Trần Phước Lộc',
    'Trần Thị Khánh Ly',
    'Nguyễn Văn Mẫn',
    'Nguyễn Công Minh',
    'Phạm Duy Nhật Minh',
    'Trần Văn Minh',
    'Lê Phú Ngọc',
    'Hứa Thị Bình Nguyên',
    'Trần Ngọc Nguyên',
    'Đặng Phước Nhân',
    'Nguyễn Văn Minh Nhân',
    'Nguyễn Văn Thành Nhân',
    'Đàm Hồng Nhật',
    'Nguyễn Đức Đại Phước',
    'Lê Hồng Phúc',
    'Phan Lâm Nhật Quang',
    'Phạm Lê Anh Quân',
    'Nguyễn Văn Quốc',
    'Trần Hữu Rin',
    'Trần Công Tài',
    'Phạm Nhật Tân',
    'Đinh Thị Thanh Thanh',
    'Nguyễn Viết Thành',
    'Nguyễn Văn Thảo',
    'Nguyễn Đức Thịnh',
    'Đới Minh Thông',
    'Lê Hoàng Thuận',
    'Đỗ Anh Tiến',
    'Hoàng Quyết Tiến',
    'Phạm Nhật Tiến',
    'Nguyễn Toàn',
    'Nguyễn Toàn',
    'Nguyễn Thị Thu Trang',
    'Nguyễn Thị Thu Trang',
    'Nguyễn Thị Thùy Trang',
    'Hồ Quang Trí',
    'Nguyễn Đình Tuấn',
    'Lê Vũ Thủy Tú',
    'Phan Trung Tú',
    'Hoàng Vũ Tâm Uyên',
    'Lê Văn Việt',
    'Võ Văn Vương',
    'Dương Tuấn Vũ',
    'Nguyễn Thị Thảo Vy',
    'Trần Lê Uyên Vy',
)


def random_customer():
    return random.choice(customer_list)
